// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sso.proto

package go_micro_srv_sso

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserRequest struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37aabceb39ca51ce, []int{0}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Userinfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string   `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Userid               string   `protobuf:"bytes,4,opt,name=userid,proto3" json:"userid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Userinfo) Reset()         { *m = Userinfo{} }
func (m *Userinfo) String() string { return proto.CompactTextString(m) }
func (*Userinfo) ProtoMessage()    {}
func (*Userinfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_37aabceb39ca51ce, []int{1}
}

func (m *Userinfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Userinfo.Unmarshal(m, b)
}
func (m *Userinfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Userinfo.Marshal(b, m, deterministic)
}
func (m *Userinfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Userinfo.Merge(m, src)
}
func (m *Userinfo) XXX_Size() int {
	return xxx_messageInfo_Userinfo.Size(m)
}
func (m *Userinfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Userinfo.DiscardUnknown(m)
}

var xxx_messageInfo_Userinfo proto.InternalMessageInfo

func (m *Userinfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Userinfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Userinfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Userinfo) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

type EmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailRequest) Reset()         { *m = EmailRequest{} }
func (m *EmailRequest) String() string { return proto.CompactTextString(m) }
func (*EmailRequest) ProtoMessage()    {}
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37aabceb39ca51ce, []int{2}
}

func (m *EmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailRequest.Unmarshal(m, b)
}
func (m *EmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailRequest.Marshal(b, m, deterministic)
}
func (m *EmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailRequest.Merge(m, src)
}
func (m *EmailRequest) XXX_Size() int {
	return xxx_messageInfo_EmailRequest.Size(m)
}
func (m *EmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailRequest proto.InternalMessageInfo

func (m *EmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type EmailResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailResponse) Reset()         { *m = EmailResponse{} }
func (m *EmailResponse) String() string { return proto.CompactTextString(m) }
func (*EmailResponse) ProtoMessage()    {}
func (*EmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37aabceb39ca51ce, []int{3}
}

func (m *EmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailResponse.Unmarshal(m, b)
}
func (m *EmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailResponse.Marshal(b, m, deterministic)
}
func (m *EmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailResponse.Merge(m, src)
}
func (m *EmailResponse) XXX_Size() int {
	return xxx_messageInfo_EmailResponse.Size(m)
}
func (m *EmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmailResponse proto.InternalMessageInfo

func (m *EmailResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_37aabceb39ca51ce, []int{4}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type AuthRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37aabceb39ca51ce, []int{5}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type AuthResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	CurrentAuthority     string   `protobuf:"bytes,4,opt,name=currentAuthority,proto3" json:"currentAuthority,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37aabceb39ca51ce, []int{6}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *AuthResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AuthResponse) GetCurrentAuthority() string {
	if m != nil {
		return m.CurrentAuthority
	}
	return ""
}

func (m *AuthResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type RegisterRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Captcha              string   `protobuf:"bytes,3,opt,name=captcha,proto3" json:"captcha,omitempty"`
	Verify               string   `protobuf:"bytes,4,opt,name=verify,proto3" json:"verify,omitempty"`
	Username             string   `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37aabceb39ca51ce, []int{7}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetCaptcha() string {
	if m != nil {
		return m.Captcha
	}
	return ""
}

func (m *RegisterRequest) GetVerify() string {
	if m != nil {
		return m.Verify
	}
	return ""
}

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type RegisterResponse struct {
	Status               int64    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37aabceb39ca51ce, []int{8}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type PasswordRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Captcha              string   `protobuf:"bytes,3,opt,name=captcha,proto3" json:"captcha,omitempty"`
	Verify               string   `protobuf:"bytes,4,opt,name=verify,proto3" json:"verify,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasswordRequest) Reset()         { *m = PasswordRequest{} }
func (m *PasswordRequest) String() string { return proto.CompactTextString(m) }
func (*PasswordRequest) ProtoMessage()    {}
func (*PasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37aabceb39ca51ce, []int{9}
}

func (m *PasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordRequest.Unmarshal(m, b)
}
func (m *PasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordRequest.Marshal(b, m, deterministic)
}
func (m *PasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordRequest.Merge(m, src)
}
func (m *PasswordRequest) XXX_Size() int {
	return xxx_messageInfo_PasswordRequest.Size(m)
}
func (m *PasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordRequest proto.InternalMessageInfo

func (m *PasswordRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *PasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *PasswordRequest) GetCaptcha() string {
	if m != nil {
		return m.Captcha
	}
	return ""
}

func (m *PasswordRequest) GetVerify() string {
	if m != nil {
		return m.Verify
	}
	return ""
}

type PasswordResponse struct {
	Status               int64    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasswordResponse) Reset()         { *m = PasswordResponse{} }
func (m *PasswordResponse) String() string { return proto.CompactTextString(m) }
func (*PasswordResponse) ProtoMessage()    {}
func (*PasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37aabceb39ca51ce, []int{10}
}

func (m *PasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordResponse.Unmarshal(m, b)
}
func (m *PasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordResponse.Marshal(b, m, deterministic)
}
func (m *PasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordResponse.Merge(m, src)
}
func (m *PasswordResponse) XXX_Size() int {
	return xxx_messageInfo_PasswordResponse.Size(m)
}
func (m *PasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordResponse proto.InternalMessageInfo

func (m *PasswordResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type StreamingRequest struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingRequest) Reset()         { *m = StreamingRequest{} }
func (m *StreamingRequest) String() string { return proto.CompactTextString(m) }
func (*StreamingRequest) ProtoMessage()    {}
func (*StreamingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37aabceb39ca51ce, []int{11}
}

func (m *StreamingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingRequest.Unmarshal(m, b)
}
func (m *StreamingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingRequest.Marshal(b, m, deterministic)
}
func (m *StreamingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingRequest.Merge(m, src)
}
func (m *StreamingRequest) XXX_Size() int {
	return xxx_messageInfo_StreamingRequest.Size(m)
}
func (m *StreamingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingRequest proto.InternalMessageInfo

func (m *StreamingRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type StreamingResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingResponse) Reset()         { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()    {}
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37aabceb39ca51ce, []int{12}
}

func (m *StreamingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingResponse.Unmarshal(m, b)
}
func (m *StreamingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingResponse.Marshal(b, m, deterministic)
}
func (m *StreamingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingResponse.Merge(m, src)
}
func (m *StreamingResponse) XXX_Size() int {
	return xxx_messageInfo_StreamingResponse.Size(m)
}
func (m *StreamingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingResponse proto.InternalMessageInfo

func (m *StreamingResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Ping struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_37aabceb39ca51ce, []int{13}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type Pong struct {
	Stroke               int64    `protobuf:"varint,1,opt,name=stroke,proto3" json:"stroke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_37aabceb39ca51ce, []int{14}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

func init() {
	proto.RegisterType((*UserRequest)(nil), "go.micro.srv.sso.UserRequest")
	proto.RegisterType((*Userinfo)(nil), "go.micro.srv.sso.Userinfo")
	proto.RegisterType((*EmailRequest)(nil), "go.micro.srv.sso.EmailRequest")
	proto.RegisterType((*EmailResponse)(nil), "go.micro.srv.sso.EmailResponse")
	proto.RegisterType((*Message)(nil), "go.micro.srv.sso.Message")
	proto.RegisterType((*AuthRequest)(nil), "go.micro.srv.sso.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "go.micro.srv.sso.AuthResponse")
	proto.RegisterType((*RegisterRequest)(nil), "go.micro.srv.sso.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "go.micro.srv.sso.RegisterResponse")
	proto.RegisterType((*PasswordRequest)(nil), "go.micro.srv.sso.PasswordRequest")
	proto.RegisterType((*PasswordResponse)(nil), "go.micro.srv.sso.PasswordResponse")
	proto.RegisterType((*StreamingRequest)(nil), "go.micro.srv.sso.StreamingRequest")
	proto.RegisterType((*StreamingResponse)(nil), "go.micro.srv.sso.StreamingResponse")
	proto.RegisterType((*Ping)(nil), "go.micro.srv.sso.Ping")
	proto.RegisterType((*Pong)(nil), "go.micro.srv.sso.Pong")
}

func init() {
	proto.RegisterFile("sso.proto", fileDescriptor_37aabceb39ca51ce)
}

var fileDescriptor_37aabceb39ca51ce = []byte{
	// 583 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0x71, 0x92, 0x26, 0x93, 0x42, 0xc3, 0xaa, 0xaa, 0x22, 0x23, 0x5a, 0x58, 0x90, 0x08,
	0x3d, 0x58, 0x15, 0xbc, 0x00, 0x08, 0x81, 0x10, 0x12, 0xa8, 0x4a, 0xe8, 0x81, 0xe3, 0x36, 0xd9,
	0xba, 0x56, 0x63, 0x6f, 0xd8, 0x59, 0xa7, 0xca, 0x6b, 0xc0, 0xab, 0xf0, 0x80, 0x68, 0xff, 0x6c,
	0x37, 0x75, 0xc2, 0x8d, 0xdb, 0x7e, 0x3b, 0x9f, 0x67, 0xbe, 0x99, 0xfd, 0x32, 0x81, 0x3e, 0xa2,
	0x88, 0x97, 0x52, 0x28, 0x41, 0x86, 0x89, 0x88, 0xb3, 0x74, 0x26, 0x45, 0x8c, 0x72, 0x15, 0x23,
	0x0a, 0x7a, 0x02, 0x83, 0x0b, 0xe4, 0x72, 0xc2, 0x7f, 0x16, 0x1c, 0x15, 0x19, 0x42, 0x98, 0x61,
	0x32, 0x0a, 0x9e, 0x05, 0xe3, 0xfe, 0x44, 0x1f, 0xe9, 0x1c, 0x7a, 0x9a, 0x90, 0xe6, 0x57, 0x82,
	0x10, 0x68, 0xe7, 0x2c, 0xe3, 0x2e, 0x6c, 0xce, 0xe4, 0x08, 0xba, 0x6c, 0xc5, 0x14, 0x93, 0xa3,
	0x07, 0xe6, 0xd6, 0x21, 0x72, 0x08, 0x1d, 0x9e, 0xb1, 0x74, 0x31, 0x0a, 0xcd, 0xb5, 0x05, 0x9a,
	0x5d, 0xe8, 0x6c, 0xf3, 0x51, 0xdb, 0xb2, 0x2d, 0xa2, 0x2f, 0x61, 0xff, 0xa3, 0x26, 0x78, 0x1d,
	0xe5, 0xd7, 0x41, 0xed, 0x6b, 0xfa, 0x0a, 0x1e, 0x3a, 0x16, 0x2e, 0x45, 0x8e, 0xa6, 0xb8, 0xe4,
	0x58, 0x2c, 0x94, 0xe1, 0xf5, 0x26, 0x0e, 0xd1, 0x27, 0xb0, 0xf7, 0x95, 0x23, 0xb2, 0x84, 0xeb,
	0x8e, 0x90, 0xad, 0x7d, 0x47, 0xc8, 0xd6, 0x54, 0xc0, 0xe0, 0x7d, 0xa1, 0xae, 0x7d, 0xa9, 0x08,
	0x7a, 0x5a, 0x44, 0xad, 0xb1, 0x12, 0xeb, 0xd8, 0x92, 0x21, 0xde, 0x0a, 0x39, 0x77, 0xed, 0x95,
	0x78, 0x4b, 0x83, 0x04, 0xda, 0x6a, 0xbd, 0xe4, 0xae, 0x3d, 0x73, 0xa6, 0xbf, 0x02, 0xd8, 0xb7,
	0x15, 0x9d, 0xec, 0x43, 0xe8, 0x28, 0x71, 0xc3, 0x73, 0xdf, 0x9d, 0x01, 0xba, 0x19, 0x54, 0x4c,
	0x15, 0xe8, 0x27, 0x69, 0x51, 0x99, 0x32, 0xac, 0x52, 0x92, 0x53, 0x18, 0xce, 0x0a, 0x29, 0x79,
	0xae, 0x74, 0x62, 0x21, 0x53, 0xb5, 0x76, 0x25, 0xef, 0xdd, 0x57, 0x42, 0x3b, 0xf5, 0x59, 0xfe,
	0x0e, 0xe0, 0x60, 0xc2, 0x93, 0x14, 0x55, 0xf5, 0xfa, 0x47, 0xd0, 0xcd, 0xc4, 0x65, 0xba, 0xf0,
	0x83, 0x70, 0x68, 0xe7, 0x18, 0x46, 0xb0, 0x37, 0x63, 0x4b, 0x35, 0xbb, 0x66, 0x4e, 0xa0, 0x87,
	0x3a, 0xdb, 0x8a, 0xcb, 0xf4, 0xca, 0x2b, 0x73, 0xe8, 0xce, 0xc0, 0x3b, 0x77, 0x07, 0x4e, 0x4f,
	0x61, 0x58, 0x89, 0xaa, 0x1e, 0xb9, 0x36, 0x97, 0xd0, 0xcf, 0x85, 0xde, 0xc2, 0xc1, 0xb9, 0x53,
	0xf1, 0x5f, 0x1b, 0xd0, 0x22, 0xab, 0xc2, 0xff, 0x10, 0x39, 0x86, 0xe1, 0x54, 0x49, 0xce, 0xb2,
	0x34, 0x4f, 0x6a, 0xe6, 0x9e, 0x89, 0x22, 0xb7, 0xa6, 0x0d, 0x27, 0x16, 0xd0, 0xd7, 0xf0, 0xb8,
	0xc6, 0xac, 0x9c, 0xd2, 0x40, 0x3d, 0x86, 0xf6, 0x79, 0x9a, 0x27, 0xb6, 0xa8, 0x14, 0x37, 0xdc,
	0x85, 0x1d, 0x32, 0x71, 0xb1, 0x3d, 0xfe, 0xe6, 0x4f, 0x1b, 0xc2, 0x29, 0x0a, 0xf2, 0x19, 0x3a,
	0xdf, 0x8d, 0xf5, 0x9e, 0xc6, 0x9b, 0x8b, 0x21, 0xae, 0xfd, 0x44, 0xa2, 0xe3, 0x6d, 0x61, 0xab,
	0x92, 0xb6, 0xc8, 0x17, 0x18, 0x7c, 0xb0, 0xbe, 0xd3, 0xcb, 0xa2, 0x29, 0x5f, 0x6d, 0xcb, 0x44,
	0x51, 0x73, 0x58, 0xef, 0x18, 0xda, 0x22, 0x53, 0xe8, 0x79, 0x0f, 0x90, 0xe7, 0xf7, 0x99, 0x1b,
	0xa6, 0x8d, 0xe8, 0x2e, 0x4a, 0x29, 0xf0, 0x1b, 0xf4, 0xa7, 0x3c, 0x9f, 0x9b, 0xf5, 0x41, 0x1a,
	0xfa, 0xa9, 0x6f, 0x9f, 0xe8, 0x64, 0x6b, 0xbc, 0xcc, 0xf7, 0x03, 0x1e, 0x7d, 0x12, 0x32, 0xe1,
	0xca, 0x3b, 0xa1, 0x49, 0xea, 0x86, 0x3d, 0x9b, 0xa4, 0x6e, 0x1a, 0x89, 0xb6, 0xc8, 0x05, 0x74,
	0xad, 0x11, 0x48, 0x03, 0x7f, 0xd3, 0x4c, 0xd1, 0x8b, 0x9d, 0x1c, 0x9f, 0xf4, 0x2c, 0x20, 0xef,
	0xa0, 0xa7, 0x4d, 0x63, 0x8d, 0xd1, 0x20, 0x24, 0xcd, 0x93, 0xa8, 0xe9, 0x5e, 0xe4, 0x09, 0x6d,
	0x8d, 0x83, 0xb3, 0xe0, 0xb2, 0x6b, 0xfe, 0x44, 0xde, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xf1,
	0xcb, 0xcd, 0x12, 0x51, 0x06, 0x00, 0x00,
}
